# Generated by Django 3.1.3 on 2020-11-27 19:35

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command('loaddata', 'clubs.json')
    call_command('loaddata', 'positions.json')
    # call_command('loaddata', 'players.json')


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
